import { describe,it,expect } from 'vitest';
import { createStore,parseState,KEY } from '../src/data/store';
import { monthlyReport } from '../src/data/reports';
const setup=()=>{const data=new Map<string,string>();const storage={getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v);}};return {storage,store:createStore(storage)};};
describe('shared materials catalogue',()=>{
 it('migrates old records without losing receipts',()=>{const {store}=setup();const old=JSON.parse(JSON.stringify(store.getSnapshot()));delete old.materials;const migrated=parseState(old);expect(migrated.receipts).toEqual(old.receipts);expect(migrated.materials.length).toBeGreaterThan(0);expect(parseState(migrated).materials).toEqual(migrated.materials);});
 it('persists a general material and rejects duplicates',()=>{const {store,storage}=setup();const material=store.saveMaterial({name:'Anchor bolt',unit:'Piece',category:'Hardware'});expect(createStore(storage).getSnapshot().materials.find(m=>m.id===material.id)?.name).toBe('Anchor bolt');expect(()=>store.saveMaterial({name:' anchor   BOLT ',unit:'Piece',category:'Hardware'})).toThrow(/already/i);});
 it('rejects archived material on new receipts and keeps history',()=>{const {store}=setup();const m=store.saveMaterial({name:'Review bolt',unit:'Piece',category:'Hardware'});const input={vendor:'v1',site:'s1',date:'2024-06-12',payment:'Unpaid' as const,paid:0,image:'',reference:'CAT-1',notes:'',items:[{materialId:m.id,description:m.name,unit:m.unit,quantity:2,rate:10}]};store.addReceipt(input);store.toggleMaterial(m.id);expect(()=>store.addReceipt({...input,reference:'CAT-2'})).toThrow(/active material/i);expect(store.getSnapshot().receipts.find(r=>r.reference==='CAT-1')?.items[0].description).toBe('Review bolt');});
});
it('reports billing month separately from actual payment month',()=>{const {store}=setup();const r=store.addReceipt({vendor:'v1',site:'s1',date:'2024-06-12',payment:'Partial',paid:20,image:'',reference:'RPT-1',notes:'',items:[{description:'Report item',quantity:1,unit:'Piece',rate:100}]});const state=structuredClone(store.getSnapshot());const receipt=state.receipts.find(x=>x.id===r.id)!;receipt.paid=70;receipt.payments.push({date:'2024-07-01',amount:50});const report=monthlyReport([receipt],2024);expect(report.find(x=>x.month==='2024-06')).toMatchObject({billed:100,paid:70,outstanding:30,cashPaid:20});expect(report.find(x=>x.month==='2024-07')).toMatchObject({billed:0,cashPaid:50});});
