import { useState, useEffect } from 'react';
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, Tooltip, CartesianGrid, PieChart, Pie, Cell, BarChart, Bar } from 'recharts';
import { useLedger } from '../context';
import { balance, categories, today, total } from '../data/store';
import { money } from '../lib';
import { Empty, Panel, Tabs } from '../components/ui';
function useChartMotion(){const [enabled,setEnabled]=useState(false);useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setEnabled(!media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);return enabled;}
export const chartColors=['#087f6b','#347bea','#d99a00','#7544de','#00a6ae','#2563eb','#b67800','#168548'];
export function CategoryChart({compact=false}:{compact?:boolean}){const {state}=useLedger();const motion=useChartMotion();const rows=state.receipts.filter(r=>r.date.startsWith(today().slice(0,7)));const data=categories.map((name,i)=>({name,color:chartColors[i],value:rows.filter(r=>state.vendors.find(v=>v.id===r.vendor)?.category===name).reduce((n,r)=>n+total(r),0)})).filter(x=>x.value>0);return data.length?<div className={`category-chart ${compact?'compact':''}`}><div className="pie-wrap"><ResponsiveContainer width="100%" height={195}><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={61} outerRadius={78} paddingAngle={4} cornerRadius={6} isAnimationActive={motion} animationDuration={650}>{data.map(d=><Cell key={d.name} fill={d.color}/>)}</Pie><Tooltip formatter={v=>money(Number(v))}/></PieChart></ResponsiveContainer><div className="pie-label"><strong>{money(balance(rows).billed).replace('Rs ','')}</strong><span>Rs billed this month</span></div></div><div className="legend">{data.map(d=><div className="legend-row" key={d.name}><span className="dot" style={{background:d.color}}/>{d.name}<strong>{money(d.value)}</strong></div>)}</div></div>:<Empty title="No spend this month">Add a receipt to see the material mix.</Empty>;}
export function SpendChart(){const {state}=useLedger();const motion=useChartMotion();const [range,setRange]=useState('6 months');const count=range==='6 months'?6:12;const data=Array.from({length:count},(_,i)=>{const date=new Date();date.setDate(1);date.setMonth(date.getMonth()-count+1+i);const key=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;return {month:date.toLocaleDateString('en-GB',{month:'short'}),full:date.toLocaleDateString('en-GB',{month:'long',year:'numeric'}),value:balance(state.receipts.filter(r=>r.date.startsWith(key))).billed};});return <Panel title="The bigger picture" subtitle="Material spend over time · by receipt date" action={<Tabs values={['6 months','12 months']} value={range} onChange={setRange}/>}><div className="chart-frame" role="img" aria-label={`Spending over ${range}. Monthly figures are available below.`}><ResponsiveContainer width="100%" height={255}><AreaChart data={data} margin={{left:5,right:20,top:15,bottom:0}}><defs><linearGradient id="spend-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#087f6b" stopOpacity={.18}/><stop offset="100%" stopColor="#087f6b" stopOpacity={.01}/></linearGradient></defs><CartesianGrid stroke="#e8eeea" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fontSize:11,fill:'#62716f'}}/><YAxis axisLine={false} tickLine={false} width={65} tick={{fontSize:10,fill:'#62716f'}} tickFormatter={v=>v>=1e7?`${v/1e7} Cr`:`${v/1e5} L`}/><Tooltip formatter={v=>money(Number(v))} labelFormatter={(_,p)=>p[0]?.payload?.full??''}/><Area type="monotone" dataKey="value" name="Materials billed" stroke="#087f6b" strokeWidth={3} fill="url(#spend-fill)" isAnimationActive={motion} animationDuration={650}/></AreaChart></ResponsiveContainer></div><details className="chart-data"><summary>View monthly figures</summary><dl>{data.map(d=><div key={d.full}><dt>{d.full}</dt><dd>{money(d.value)}</dd></div>)}</dl></details></Panel>;}
export function VendorRanking(){const {state}=useLedger();const motion=useChartMotion();const [by,setBy]=useState('Spend');const data=state.vendors.map(v=>({name:v.name.replace(/ Traders| Supply| & Ceramics| House| Interior & Decor/g,''),value:balance(state.receipts.filter(r=>r.vendor===v.id))[by==='Spend'?'billed':'outstanding']})).filter(v=>v.value>0).sort((a,b)=>b.value-a.value).slice(0,5);return <Panel title="Vendor overview" subtitle={`Top suppliers by ${by.toLowerCase()}`} action={<Tabs values={['Spend','Outstanding']} value={by} onChange={setBy}/>}><div className="chart-frame"><ResponsiveContainer width="100%" height={245}><BarChart data={data} margin={{left:5,right:20,top:15,bottom:10}}><CartesianGrid stroke="#e8eeea" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="name" tick={{fontSize:10,fill:'#62716f'}} axisLine={false} tickLine={false} interval={0} tickFormatter={v=>String(v).split(' ').slice(0,2).join(' ')}/><YAxis tickFormatter={v=>`${v/1e5} L`} axisLine={false} tickLine={false} tick={{fontSize:10}} width={60}/><Tooltip formatter={v=>money(Number(v))}/><Bar dataKey="value" name={by} radius={[7,7,0,0]} maxBarSize={44} isAnimationActive={motion} animationDuration={650}>{data.map((d,i)=><Cell key={d.name} fill={chartColors[i%chartColors.length]}/>)}</Bar></BarChart></ResponsiveContainer></div><details className="chart-data"><summary>View vendor figures</summary><dl>{data.map(d=><div key={d.name}><dt>{d.name}</dt><dd>{money(d.value)}</dd></div>)}</dl></details></Panel>;}
