import { useState,type FormEvent } from 'react';
import { Link,useParams } from 'react-router-dom';
import { ArrowUpRight,ArrowLeft,MapPin,Pencil,Building2,Phone,Mail } from 'lucide-react';
import { useLedger,useToast } from '../context';
import { type Company } from '../data/store';
import { money,errorText } from '../lib';
import { SiteCard } from './Sites';
import { Heading,Button,Modal,ErrorMessage,Empty,SiteImage,Badge } from '../components/ui';
export default function Showcase({preview=false}:{preview?:boolean}){const {state}=useLedger();const [edit,setEdit]=useState(false);const projects=state.sites.filter(s=>s.featured),completed=state.sites.filter(s=>s.status==='Completed');const company=state.company;return <>{preview?<Heading eyebrow="YOUR PUBLIC PORTFOLIO" title="Let your work speak for itself." actions={<><Button onClick={()=>setEdit(true)}><Pencil/>Company details</Button><Link className="button primary" to="/showcase"><ArrowUpRight size={17}/>Open public preview</Link></>}>Projects marked Featured on the Sites page appear here automatically.</Heading>:<PublicHeader/>}<section className="portfolio-hero"><div><p className="eyebrow">SURELY · RESIDENTIAL CONSTRUCTION</p><h1>{company.tagline}</h1><p>{company.about}</p><a href="#featured-projects" className="button primary">Explore our projects<ArrowUpRight size={18}/></a></div><div className="hero-illustration">{projects[0]?<SiteImage site={projects[0]}/>:<Building2 size={90}/>}<span className="hero-stamp">BUILT ON TRUST<br/><strong>Every detail matters.</strong></span></div></section><section className="portfolio-stats"><div><strong>{String(completed.length).padStart(2,'0')}</strong><span>Projects completed</span></div><div><strong>{money(completed.reduce((n,s)=>n+s.value,0))}</strong><span>Completed project value · estimates</span></div><div><strong>{company.foundingYear!==null?`${new Date().getFullYear()-company.foundingYear}+`:'—'}</strong><span>{company.foundingYear!==null?'Years in business':'Founding year not yet provided'}</span></div></section><section id="featured-projects" className="portfolio-projects"><p className="eyebrow">A SELECTION OF OUR WORK</p><h2>Spaces made for living.</h2><p className="muted">Thoughtful homes. Considered finishes. Lasting relationships.</p><div className="site-grid">{projects.map(site=><SiteCard key={site.id} site={site} publicView/>)}</div>{!projects.length&&<Empty title="Our portfolio is taking shape">Featured projects will appear here.</Empty>}</section><section className="portfolio-contact"><div><p className="eyebrow">YOUR NEXT CHAPTER</p><h2>Let’s build something worth coming home to.</h2></div><div>{company.phone&&<a className="button primary" href={`tel:${company.phone.replace(/[^+0-9]/g,'')}`}><Phone size={17}/>{company.phone}</a>}{company.email&&<a className="button" href={`mailto:${company.email}`}><Mail size={17}/>Email us</a>}{!company.phone&&!company.email&&<p className="muted">Company contact details will be added before publication.</p>}</div></section>{!preview&&<PublicFooter/>}{edit&&<CompanyForm onClose={()=>setEdit(false)}/>}</>;}
export function PublicHeader(){return <header className="public-header"><Link to="/showcase" className="public-brand"><img className="company-logo" src="/surely-white.jpg" alt="CMS by Surely logo"/><span>CMS by Surely<small className="brand-subtitle">Construction workspace</small></span></Link><nav><Link to="/showcase">Our projects</Link><Link to="/portfolio" className="button">Return to workspace</Link></nav></header>;}
export function PublicFooter(){return <footer className="public-footer"><strong>CMS by Surely · Construction workspace</strong><span>Frontend portfolio prototype · Sample projects are illustrative.</span></footer>;}
export function PublicProject(){const {id}=useParams();const {state}=useLedger();const site=state.sites.find(s=>s.id===id&&s.featured);return <><PublicHeader/><div className="public-project"><Link className="back-link" to="/showcase"><ArrowLeft size={16}/>All featured projects</Link>{site?<><Heading eyebrow="A SURELY RESIDENCE" title={site.name}><MapPin size={16}/> {site.location}</Heading><div className="public-project-image"><SiteImage site={site}/></div><div className="project-facts"><div><small>Project status</small><Badge>{site.status}</Badge></div><div><small>Plot number</small><strong>{site.plot}</strong></div><div><small>Estimated project value</small><strong>{money(site.value)}</strong></div></div><section className="project-description"><p className="eyebrow">THE PROJECT</p><h2>Built with care, from the ground up.</h2><p className="preserve-lines">{site.description||'More information about this residence will be added soon.'}</p></section></>:<Empty title="Project not available">This project is not currently featured in the portfolio.</Empty>}</div><PublicFooter/></>;}
function CompanyForm({onClose}:{onClose:()=>void}){const {state,store}=useLedger();const notify=useToast();const [error,setError]=useState('');function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const raw=Object.fromEntries(new FormData(e.currentTarget));try{store.saveCompany({...raw,foundingYear:raw.foundingYear?Number(raw.foundingYear):null} as Company);notify('Company profile updated.');onClose();}catch(e){setError(errorText(e));}}return <Modal title="Company details" subtitle="Use verified company information for the public preview." onClose={onClose}><form onSubmit={submit}><div className="dialog-body form-grid"><label className="form-field full"><span className="bilingual-label"><span>Tagline *</span><span lang="ur" dir="rtl">تعارفی جملہ</span></span><input name="tagline" required maxLength={160} defaultValue={state.company.tagline}/></label><label className="form-field full"><span className="bilingual-label"><span>About the company</span><span lang="ur" dir="rtl">کمپنی کا تعارف</span></span><textarea name="about" rows={4} maxLength={2500} defaultValue={state.company.about}/></label><label className="form-field"><span className="bilingual-label"><span>Founding year</span><span lang="ur" dir="rtl">قیام کا سال</span></span><input name="foundingYear" type="number" min="1900" max={new Date().getFullYear()} defaultValue={state.company.foundingYear??''}/></label><label className="form-field"><span className="bilingual-label"><span>Contact number</span><span lang="ur" dir="rtl">رابطہ نمبر</span></span><input name="phone" type="tel" maxLength={30} defaultValue={state.company.phone}/></label><label className="form-field full"><span className="bilingual-label"><span>Contact email</span><span lang="ur" dir="rtl">ای میل</span></span><input name="email" type="email" defaultValue={state.company.email}/></label><div className="full"><ErrorMessage error={error}/></div></div><div className="dialog-foot"><Button onClick={onClose}>Cancel</Button><Button type="submit" tone="primary">Save company details</Button></div></form></Modal>;}
