import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Building2, TrendingUp, Layers, Star, Plus, Download, Grid2X2, List, MapPin, ArrowLeft, Pencil, Printer, Store, Wallet } from 'lucide-react';
import { useLedger, useToast } from '../context';
import { balance, today, type Site } from '../data/store';
import { money, csv, formatDate, errorText } from '../lib';
import { Heading, Metric, Panel, Button, Tabs, SearchBox, Badge, SiteImage, Empty, DetailLink, VendorIcon } from '../components/ui';
import { SiteForm } from '../components/Forms';
import SiteActivity from '../components/SiteActivity';
import ReceiptTable from '../components/ReceiptTable';

export function SiteCard({site,publicView=false}:{site:Site;publicView?:boolean}){
  const {state,store}=useLedger();const notify=useToast();const rows=state.receipts.filter(r=>r.site===site.id);const url=publicView?`/showcase/${site.id}`:`/sites/${site.id}`;
  return <article className="site-card"><div className="site-cover"><Link to={url} aria-label={`View ${site.name}`}><SiteImage site={site}/></Link><Badge>{site.status}</Badge>{!publicView&&<button className="feature-button" aria-label={`${site.featured?'Unfeature':'Feature'} ${site.name}`} aria-pressed={site.featured} onClick={()=>{try{store.featureSite(site.id);notify(site.featured?'Removed from showcase.':'Added to showcase.');}catch(e){notify(errorText(e));}}}><Star size={17}/></button>}</div><div className="site-body"><p className="site-plot">PLOT {site.plot}</p><h3><Link to={url}>{site.name}</Link></h3><p className="site-location"><MapPin size={13}/>{site.location}</p><div className="site-stats"><div><small>Estimated project value</small><strong>{money(site.value)}</strong></div>{!publicView&&<div><small>Materials billed</small><strong>{money(balance(rows).billed)}</strong></div>}</div><div className="site-bottom"><span>{publicView?'Residential construction':`${new Set(rows.map(r=>r.vendor)).size} vendors · ${rows.length} receipts`}</span><DetailLink to={url}>View {publicView?'project':'site'}</DetailLink></div></div></article>;
}
export default function Sites(){const {state}=useLedger();const [query,setQuery]=useState(''),[status,setStatus]=useState('All sites'),[list,setList]=useState(false),[add,setAdd]=useState(false);const sites=state.sites.filter(s=>(status==='All sites'||s.status===status)&&`${s.name} ${s.plot} ${s.location}`.toLowerCase().includes(query.toLowerCase()));return <><Heading eyebrow="FROM FOUNDATION TO FINISH" title="Every site. One clear picture." actions={<><Button onClick={()=>csv('surely-cms-sites.csv',[['Site','Plot','Location','Status','Estimated value (Rs)'],...sites.map(s=>[s.name,s.plot,s.location,s.status,s.value])])}><Download/>Export</Button><Button tone="primary" onClick={()=>setAdd(true)}><Plus/>Add site</Button></>}>Keep your plots, material costs, and finest work connected.</Heading><div className="metrics"><Metric title="Active sites" value={state.sites.filter(s=>s.status==='Active').length} note={`${state.sites.length} projects in your portfolio`} icon={<Building2/>}/><Metric title="Estimated project value" value={money(state.sites.reduce((n,s)=>n+s.value,0))} note="Combined value of all sites" icon={<TrendingUp/>} tone="blue"/><Metric title="Materials billed" value={money(balance(state.receipts).billed)} note="All recorded purchases" icon={<Layers/>} tone="purple"/><Metric title="Featured projects" value={state.sites.filter(s=>s.featured).length} note="Visible in your Showcase" icon={<Star/>} tone="amber"/></div><div className="sites-controls"><Tabs values={['All sites','Active','Completed','On Hold']} value={status} onChange={setStatus}/><div className="filters"><SearchBox value={query} onChange={setQuery} label="Search sites" placeholder="Search site or plot number…"/><div className="view-switch"><button className={!list?'selected':''} aria-label="Grid view" aria-pressed={!list} onClick={()=>setList(false)}><Grid2X2 size={17}/></button><button className={list?'selected':''} aria-label="List view" aria-pressed={list} onClick={()=>setList(true)}><List size={17}/></button></div></div></div><section className={`site-grid ${list?'list':''}`}>{sites.map(s=><SiteCard key={s.id} site={s}/>)}{!query&&status==='All sites'&&<div className="site-new"><span className="add-circle"><Plus/></span><h3>The next great build starts here.</h3><p>Add a new plot and connect every vendor and receipt from day one.</p><Button onClick={()=>setAdd(true)}><Plus/>Add your next site</Button></div>}</section>{!sites.length&&<Empty title="No sites found">Try another search or create your first construction site.</Empty>}<p className="form-hint">Showing {sites.length} of {state.sites.length} sites · Star a site to show it in your public portfolio.</p>{add&&<SiteForm onClose={()=>setAdd(false)}/>}</>;}

export function SiteDetail(){const {id}=useParams();const {state,store}=useLedger();const notify=useToast();const [edit,setEdit]=useState(false);const s=state.sites.find(s=>s.id===id);if(!s)return <Empty title="Site not found" action={<Link className="button" to="/sites">All sites</Link>}/>;const rows=state.receipts.filter(r=>r.site===s.id),b=balance(rows),vendors=state.vendors.filter(v=>rows.some(r=>r.vendor===v.id));return <><Link className="back-link" to="/sites"><ArrowLeft size={16}/>All sites</Link><Heading eyebrow={`PLOT ${s.plot} · ${s.status}`} title={s.name} actions={<><Button onClick={()=>setEdit(true)}><Pencil/>Edit site</Button><Button onClick={()=>window.print()}><Printer/>Print</Button><Link className="button primary" to={`/receipts/new?site=${s.id}`}><Plus size={16}/>New receipt</Link></>}>{s.location}</Heading><div className="metrics"><Metric title="Estimated value" value={money(s.value)} note="Project estimate" icon={<TrendingUp/>}/><Metric title="Materials billed" value={money(b.billed)} note={`${rows.length} receipts`} icon={<Layers/>} tone="blue"/><Metric title="Outstanding" value={money(b.outstanding)} note="All unpaid material bills · واجب الادا رقم" icon={<Wallet/>} tone="amber"/><Metric title="Material bills paid" value={money(b.paid)} note="Recorded payments · ادا شدہ رقم" icon={<Wallet/>}/><Metric title="Monthly material dues" value={money(balance(rows.filter(r=>r.date.slice(0,7)===today().slice(0,7))).outstanding)} note="Unpaid this billing month · اس ماہ واجب الادا" icon={<Wallet/>} tone="amber"/><Metric title="Supplying vendors" value={vendors.length} note="Based on receipt history" icon={<Store/>} tone="purple"/></div><div className="detail-grid"><div><div className="detail-hero"><SiteImage site={s}/></div><SiteActivity siteId={s.id}/></div><aside className="side-stack"><Panel title="Site information"><div className="padded"><dl className="details-info"><div><dt>Plot number</dt><dd>{s.plot}</dd></div><div><dt>Location</dt><dd>{s.location}</dd></div><div><dt>Start date</dt><dd>{formatDate(s.start)}</dd></div><div><dt>Current status</dt><dd><Badge>{s.status}</Badge></dd></div></dl><div className="feature-setting"><div><strong>Featured project</strong><p>Visible in Showcase</p></div><button className="toggle" role="switch" aria-label="Feature project" aria-checked={s.featured} onClick={()=>{try{store.featureSite(s.id);}catch(e){notify(errorText(e));}}}/></div></div></Panel></aside></div>{edit&&<SiteForm site={s} onClose={()=>setEdit(false)}/>}</>;}
