import { useState, type FormEvent } from 'react';
import { Check } from 'lucide-react';
import { useLedger, useToast } from '../context';
import { categories, today, type Vendor, type Site, type VendorInput, type SiteInput } from '../data/store';
import { errorText } from '../lib';
import { Modal, Button, ErrorMessage, PhotoInput } from './ui';

export function VendorForm({vendor,onClose}:{vendor?:Vendor;onClose:()=>void}){
  const {store}=useLedger();const notify=useToast();const [error,setError]=useState('');
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));try{store.saveVendor(data as VendorInput,vendor?.id);notify(vendor?'Vendor details updated.':'New vendor added.');onClose();}catch(e){setError(errorText(e));}}
  return <Modal title={vendor?'Edit vendor details':'Add a new vendor'} subtitle="One account for every receipt from this supplier." onClose={onClose}><form onSubmit={submit}><div className="dialog-body"><div className="form-grid"><label className="form-field full"><span className="bilingual-label"><span>Vendor name *</span><span lang="ur" dir="rtl">فراہم کنندہ کا نام</span></span><input name="name" required maxLength={160} defaultValue={vendor?.name} placeholder="e.g. Mughal Steel Traders" autoFocus/></label><label className="form-field full"><span className="bilingual-label"><span>Material category *</span><span lang="ur" dir="rtl">سامان کی قسم</span></span><select name="category" defaultValue={vendor?.category??'Steel'}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="form-field"><span className="bilingual-label"><span>Contact person</span><span lang="ur" dir="rtl">رابطہ شخص</span></span><input name="contact" maxLength={100} defaultValue={vendor?.contact}/></label><label className="form-field"><span className="bilingual-label"><span>Phone number</span><span lang="ur" dir="rtl">فون نمبر</span></span><input name="phone" type="tel" maxLength={30} defaultValue={vendor?.phone} placeholder="0300 1234567"/></label></div><p className="form-hint">{vendor?`${vendor.code} · Existing receipts remain linked.`:'A unique vendor code will be generated when you save.'}</p><ErrorMessage error={error}/></div><div className="dialog-foot"><Button onClick={onClose}>Cancel</Button><Button type="submit" tone="primary"><Check size={16}/>Save vendor</Button></div></form></Modal>;
}
export function SiteForm({site,vendorId,onClose}:{site?:Site;vendorId?:string;onClose:()=>void}){
  const {store}=useLedger();const notify=useToast();const [error,setError]=useState(''),[image,setImage]=useState(site?.image??''),[busy,setBusy]=useState(false);
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const raw=Object.fromEntries(new FormData(e.currentTarget));try{store.saveSite({...raw,value:Number(raw.value),featured:raw.featured==='on',image} as SiteInput,site?.id,vendorId);notify(vendorId?'Site created and linked to the vendor.':'Site saved.');onClose();}catch(e){setError(errorText(e));}}
  return <Modal title={site?'Edit site details':'Add a construction site'} subtitle={vendorId?'This site will be linked to the current vendor.':'From the first delivery to the final finish.'} onClose={onClose}><form onSubmit={submit}><div className="dialog-body"><div className="form-grid"><label className="form-field full"><span className="bilingual-label"><span>Site name *</span><span lang="ur" dir="rtl">منصوبے کا نام</span></span><input name="name" required maxLength={160} defaultValue={site?.name} autoFocus/></label><label className="form-field"><span className="bilingual-label"><span>Plot number *</span><span lang="ur" dir="rtl">پلاٹ نمبر</span></span><input name="plot" required maxLength={160} defaultValue={site?.plot}/></label><label className="form-field"><span className="bilingual-label"><span>Status *</span><span lang="ur" dir="rtl">موجودہ حالت</span></span><select name="status" defaultValue={site?.status??'Active'}>{['Active','Completed','On Hold'].map(v=><option key={v}>{v}</option>)}</select></label><label className="form-field full"><span className="bilingual-label"><span>Location / phase / block *</span><span lang="ur" dir="rtl">مقام / فیز / بلاک</span></span><input name="location" required maxLength={160} defaultValue={site?.location} placeholder="DHA Phase 6 · Block A, Lahore"/></label><label className="form-field"><span className="bilingual-label"><span>Estimated value (Rs) *</span><span lang="ur" dir="rtl">تخمینی مالیت (روپے)</span></span><input name="value" type="number" min="0" max="1000000000000" step="1" required defaultValue={site?.value}/><small>Rs 42 Cr = 420,000,000</small></label><label className="form-field"><span className="bilingual-label"><span>Start date *</span><span lang="ur" dir="rtl">آغاز کی تاریخ</span></span><input name="start" type="date" required defaultValue={site?.start??today()}/></label><label className="form-field full"><span className="bilingual-label"><span>Project description</span><span lang="ur" dir="rtl">منصوبے کی تفصیل</span></span><textarea name="description" rows={3} maxLength={2500} defaultValue={site?.description??''}/></label><label className="form-check"><input name="featured" type="checkbox" defaultChecked={site?.featured}/>Feature this project in the public Showcase</label></div><PhotoInput value={image} onChange={setImage} label="Project photograph" onBusyChange={setBusy}/><ErrorMessage error={error}/></div><div className="dialog-foot"><Button onClick={onClose}>Cancel</Button><Button type="submit" tone="primary" disabled={busy}><Check size={16}/>Save site</Button></div></form></Modal>;
}
