import {useId,useState} from 'react';
import {useLedger} from '../context';
import type {Material} from '../data/store';
import MaterialForm from './MaterialForm';
export default function MaterialPicker({value,onSelect}:{value:string;onSelect:(material:Material|null)=>void}){
 const {state}=useLedger();const id=useId();const selected=state.materials.find(m=>m.id===value);const [query,setQuery]=useState(''),[open,setOpen]=useState(false),[add,setAdd]=useState(false),[cursor,setCursor]=useState(0);
 const rows=state.materials.filter(m=>m.active&&`${m.name} ${m.category} ${m.unit}`.toLowerCase().includes(query.toLowerCase())).slice(0,30);
 function choose(m:Material){onSelect(m);setQuery('');setOpen(false);}
 return <div className="material-picker form-field item-description" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false);}}><label htmlFor={id} className="bilingual-label"><span>Material *</span><span lang="ur" dir="rtl">سامان منتخب کریں</span></label><input id={id} role="combobox" aria-expanded={open} aria-controls={`${id}-options`} aria-autocomplete="list" aria-activedescendant={open&&rows[cursor]?`${id}-${cursor}`:undefined} value={open?query:selected?.name??''} placeholder="Search materials…" required onFocus={()=>{setQuery('');setCursor(0);setOpen(true);}} onChange={e=>{setQuery(e.target.value);setCursor(0);onSelect(null);setOpen(true);}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);return;}if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);setCursor(c=>Math.min(c+1,rows.length-1));}if(e.key==='ArrowUp'){e.preventDefault();setCursor(c=>Math.max(0,c-1));}if(e.key==='Enter'&&open){e.preventDefault();if(rows[cursor])choose(rows[cursor]);else setAdd(true);}}}/>{open&&<div className="material-options"><div id={`${id}-options`} role="listbox" aria-label="Matching materials">{rows.map((m,index)=><button type="button" role="option" aria-selected={index===cursor} id={`${id}-${index}`} key={m.id} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(m)}><strong>{m.name}</strong><small>{m.unit} · {m.category}</small></button>)}{!rows.length&&<p>No material found.</p>}</div><button type="button" className="add-material-option" onMouseDown={e=>e.preventDefault()} onClick={()=>{setOpen(false);setAdd(true);}}>Other / Add material <span lang="ur" dir="rtl">نیا سامان شامل کریں</span></button></div>}{add&&<MaterialForm initialName={query} onClose={()=>setAdd(false)} onSaved={choose}/>}</div>;
}
