import { useEffect, useRef, useState, type ReactNode, type ButtonHTMLAttributes } from 'react';
import { Link } from 'react-router-dom';
import { X, Search, Store, Layers, Paintbrush, Wrench, Star, ArrowRight, Plus, ImagePlus } from 'lucide-react';
import { imageFile, errorText } from '../lib';
import { type Site } from '../data/store';

export function Button({children,tone='',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{tone?:string}){return <button type="button" {...props} className={`button ${tone} ${props.className??''}`}>{children}</button>;}
export const Badge=({children}:{children:string})=><span className={`status ${children.toLowerCase().replaceAll(' ','-')}`}>{children}</span>;
export const Empty=({title,children,action}:{title:string;children?:ReactNode;action?:ReactNode})=><div className="empty"><Layers size={30}/><h3>{title}</h3><p>{children}</p>{action}</div>;
export function Heading({eyebrow,title,children,actions}:{eyebrow:string;title:string;children?:ReactNode;actions?:ReactNode}){return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{children&&<p>{children}</p>}</div>{actions&&<div className="heading-actions">{actions}</div>}</div>;}
export function Metric({title,value,note,icon,tone=''}:{title:string;value:ReactNode;note:ReactNode;icon:ReactNode;tone?:string}){return <article className={`metric metric-${tone}`}><div className="metric-top"><span>{title}</span><span className={`metric-icon ${tone}`}>{icon}</span></div><div className="metric-value">{value}</div><div className="metric-note">{note}</div></article>;}
export function Panel({title,subtitle,action,children,className=''}:{title:string;subtitle?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`panel ${className}`}><div className="panel-header"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>{children}</section>;}
export function SearchBox({value,onChange,placeholder,label}:{value:string;onChange:(s:string)=>void;placeholder:string;label:string}){return <label className="search"><Search size={17}/><input aria-label={label} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></label>;}
export function Tabs({values,value,onChange}:{values:string[];value:string;onChange:(v:string)=>void}){return <div className="tabs">{values.map(v=><button key={v} type="button" className="tab" aria-pressed={v===value} onClick={()=>onChange(v)}>{v}</button>)}</div>;}
export function Modal({title,subtitle,children,onClose,wide=false}:{title:string;subtitle?:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
  const ref=useRef<HTMLDialogElement>(null);const callback=useRef(onClose);callback.current=onClose;
  useEffect(()=>{const d=ref.current!;const previous=document.activeElement as HTMLElement|null;d.showModal();const cancel=(e:Event)=>{e.preventDefault();callback.current();};d.addEventListener('cancel',cancel);return()=>{d.removeEventListener('cancel',cancel);d.close();previous?.focus();};},[]);
  return <dialog ref={ref} className={wide?'wide-dialog':''} aria-labelledby="dialog-title"><div className="dialog-head"><div><h2 id="dialog-title">{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button type="button" className="icon-button" aria-label="Close dialog" onClick={onClose}><X/></button></div>{children}</dialog>;
}
export function Confirm({title,children,onConfirm,onClose,label='Confirm'}:{title:string;children:ReactNode;onConfirm:()=>void;onClose:()=>void;label?:string}){
  const [error,setError]=useState('');return <Modal title={title} onClose={onClose}><div className="dialog-body dialog-copy">{children}<ErrorMessage error={error}/></div><div className="dialog-foot"><Button onClick={onClose}>Cancel</Button><Button tone="primary" onClick={()=>{try{onConfirm();onClose();}catch(e){setError(errorText(e));}}}>{label}</Button></div></Modal>;
}
export const ErrorMessage=({error}:{error:string})=>error?<p className="form-error" role="alert">{error}</p>:null;
export function VendorIcon({category}:{category:string}){const Icon=category==='Paint'?Paintbrush:category==='Hardware'||category==='Fasteners'?Wrench:category==='Decor'?Star:category==='Steel'?Layers:Store;return <span className={`vendor-icon ${category}`}><Icon size={19}/></span>;}
export function SiteImage({site}:{site:Site}){const sample=['s1','s2','s3','s4'].indexOf(site.id);const source=site.image||(sample>=0?`/photos/site-${sample+1}.jpg`:`/illustrations/villa-${site.style}.svg`);return <div className="site-art"><img src={source} alt={site.image?site.name:sample>=0?'Sample residence photograph — illustrative project imagery':'Architectural concept illustration — not a project photograph'} loading="lazy"/>{!site.image&&<span className="art-label">{sample>=0?'Sample photograph':'Concept illustration'}</span>}</div>;}
export function PhotoInput({value,onChange,label='Attach a photo',camera=false,onBusyChange}:{value:string;onChange:(s:string)=>void;label?:string;camera?:boolean;onBusyChange?:(busy:boolean)=>void}){
  const [error,setError]=useState(''),[busy,setBusy]=useState(false);const file=useRef<HTMLInputElement>(null),capture=useRef<HTMLInputElement>(null);
  const handle=async(selected?:File)=>{if(!selected)return;setError('');setBusy(true);onBusyChange?.(true);try{onChange(await imageFile(selected));}catch(e){setError(errorText(e));}finally{setBusy(false);onBusyChange?.(false);}};
  return <div className="photo-input"><div className="upload-box">{value?<img src={value} alt="Selected evidence preview"/>:<ImagePlus size={30}/>}<strong>{label}</strong><span>JPEG, PNG or WebP · up to 12 MB · compressed for this browser</span><div className="heading-actions"><Button disabled={busy} onClick={()=>file.current?.click()}><Plus size={16}/>{busy?'Processing…':value?'Replace photo':'Choose photo'}</Button>{camera&&<Button disabled={busy} onClick={()=>capture.current?.click()}>Take photo</Button>}{value&&<Button disabled={busy} onClick={()=>onChange('')}>Remove</Button>}</div><input ref={file} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>{void handle(e.target.files?.[0]);e.target.value='';}}/><input ref={capture} type="file" accept="image/jpeg,image/png,image/webp" capture="environment" hidden onChange={e=>{void handle(e.target.files?.[0]);e.target.value='';}}/></div><ErrorMessage error={error}/>{busy&&<p role="status">Preparing the image. Please wait before saving.</p>}</div>;
}
export const DetailLink=({to,children}:{to:string;children:ReactNode})=><Link className="text-button" to={to}>{children}<ArrowRight size={15}/></Link>;
