import {jsPDF} from 'jspdf';
import autoTable from 'jspdf-autotable';
import type {ReportData} from './data/reportDocument';
import {exactMoney} from './lib';
export type RasterText=(value:string,widthMm:number)=>{image:string;heightMm:number};
const needsShaping=(value:string)=>/[\u0600-\u06ff]/.test(value);
export async function createReportPDF(data:ReportData,rasterText?:RasterText){
 const pdf=new jsPDF({unit:'mm',format:'a4'});const logo=await fetch('/surely-white.jpg');if(!logo.ok)throw Error('Company logo could not be loaded. Please try again.');const bytes=new Uint8Array(await logo.arrayBuffer());
 const shaped=[data.scope,...data.rows.flat()].some(needsShaping);
 if(shaped&&!rasterText)throw Error('Urdu text needs browser font rendering. Use Print / Save as PDF.');
 const header=()=>{pdf.addImage(bytes,'PNG',15,12,15,15);pdf.setFont('helvetica','bold');pdf.setFontSize(15);pdf.setTextColor('#18372f');pdf.text('CMS by Surely',34,19);pdf.setFontSize(7);pdf.setFont('helvetica','normal');pdf.setTextColor('#9a7839');pdf.text('LUXURY HOMES',34,25);pdf.setTextColor('#18372f');pdf.setDrawColor('#087f6b');pdf.line(15,32,195,32);};header();
 pdf.setFontSize(22);pdf.setFont('helvetica','bold');pdf.text(data.title,15,45);pdf.setFontSize(13);pdf.text(data.period,15,54);pdf.setFont('helvetica','normal');pdf.setFontSize(9);const scope=needsShaping(data.scope)?[]:pdf.splitTextToSize(data.scope,180);if(scope.length)pdf.text(scope,15,62);if(needsShaping(data.scope)){const rendered=rasterText!(data.scope,180);pdf.addImage(rendered.image,'PNG',15,58,180,rendered.heightMm);}const summaryY=65+Math.max(scope.length*5,needsShaping(data.scope)?rasterText!(data.scope,180).heightMm:0);
 [['TOTAL BILLED',data.totals.billed,'#18372f'],['PAID AGAINST BILLS',data.totals.paid,'#087443'],['REMAINING PAYABLE',data.totals.outstanding,data.totals.outstanding?'#b42318':'#087443']].forEach(([label,value,color],i)=>{const x=15+i*61;pdf.setFillColor('#f3f7f5');pdf.roundedRect(x,summaryY,58,24,3,3,'F');pdf.setFont('helvetica','normal');pdf.setFontSize(7);pdf.setTextColor('#53655f');pdf.text(String(label),x+4,summaryY+7);pdf.setTextColor(String(color));pdf.setFontSize(11);pdf.text(exactMoney(Number(value)),x+4,summaryY+17);});
 const renderedCells=new Map<string,ReturnType<RasterText>>();
 autoTable(pdf,{startY:summaryY+32,head:[data.headers],body:data.rows.length?data.rows:[['No activity in this period',...data.headers.slice(1).map(()=>'-')]],margin:{left:15,right:15,top:39,bottom:22},styles:{font:'helvetica',fontSize:8,cellPadding:3.5,overflow:'linebreak'},headStyles:{font:'helvetica',fillColor:'#087f6b',textColor:'#ffffff',fontStyle:'bold'},alternateRowStyles:{fillColor:'#f3f7f5'},columnStyles:{0:{cellWidth:43}},rowPageBreak:'avoid',didParseCell:hook=>{if(hook.section==='body'&&typeof hook.cell.raw==='string'&&needsShaping(hook.cell.raw)){const key=`${hook.row.index}:${hook.column.index}`;const rendered=rasterText!(hook.cell.raw,hook.column.index===0?39:25);renderedCells.set(key,rendered);hook.cell.text=[''];hook.cell.styles.minCellHeight=Math.max(13,rendered.heightMm+2);}},didDrawCell:hook=>{if(hook.section==='body'){const rendered=renderedCells.get(`${hook.row.index}:${hook.column.index}`);if(rendered)pdf.addImage(rendered.image,'PNG',hook.cell.x+1,hook.cell.y+1,Math.min(hook.cell.width-2,hook.column.index===0?39:25),rendered.heightMm);}},didDrawPage:()=>{if(pdf.getNumberOfPages()>1)header();}});
 let y=(pdf as jsPDF & {lastAutoTable:{finalY:number}}).lastAutoTable.finalY+10;if(y>235){pdf.addPage();header();y=43;}pdf.setTextColor('#53655f');pdf.setFont('helvetica','normal');pdf.setFontSize(8);pdf.text(pdf.splitTextToSize(data.note,180),15,y);y+=28;['Prepared by','Checked by','Approved by'].forEach((label,i)=>{const x=15+i*62;pdf.setDrawColor('#acbbb5');pdf.line(x,y,x+52,y);pdf.text(label,x,y+5);});
 const count=pdf.getNumberOfPages();for(let page=1;page<=count;page++){pdf.setPage(page);pdf.setFont('helvetica','normal');pdf.setFontSize(7);pdf.setTextColor('#53655f');pdf.text('PKR / Material costs only / Frontend portfolio prototype',15,282);pdf.text(`${page} / ${count}`,195,282,{align:'right'});pdf.text(`Generated ${new Date().toLocaleDateString('en-GB')} from browser-local records.`,15,287);}
 return pdf;
}

export async function exportReportPDF(data:ReportData){await document.fonts.load('16px "Noto Nastaliq Urdu"');await document.fonts.ready;const rendered:RasterText=(value,widthMm)=>{const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.ceil(widthMm*4));const context=canvas.getContext('2d');if(!context)throw Error('This browser cannot render Urdu in PDF. Use Print / Save as PDF.');context.font='16px "Noto Nastaliq Urdu"';const words=value.split(/\s+/),lines:string[]=[];let line='';for(const word of words){const next=line?`${line} ${word}`:word;if(line&&context.measureText(next).width>canvas.width-12){lines.push(line);line=word;}else line=next;}if(line)lines.push(line);canvas.height=Math.max(44,lines.length*43+6);const draw=canvas.getContext('2d')!;draw.fillStyle='#263b32';draw.font='16px "Noto Nastaliq Urdu"';draw.textAlign='right';draw.direction='rtl';lines.forEach((part,index)=>draw.fillText(part,canvas.width-5,30+index*43));return {image:canvas.toDataURL('image/png'),heightMm:canvas.height/4};};const pdf=await createReportPDF(data,rendered);pdf.save(`Surely-CMS-${data.period.replace(/\s+/g,'-')}-Report.pdf`);}
